### ISSUE TITLE
Open overview when dragging items on X

### ISSUE THREAD

**Issue by seldon1000** [jdoda/hotedge#11]
When using the default GNOME hot corner, you can open overview even when dragging items like files and folders with mouse. This is extremely useful but it seems it's not yet possible with Hot Edge.

Video for reference:
https://user-images.githubusercontent.com/55358113/126033257-0176aabb-29a8-4724-b70c-c073f9123e82.mp4

System info:
Arch Linux
GNOME 40 (X11)

**Comment by jdoda** [comment]
Sorry for the delay. This does work on Wayland, but not on X. There is logic in the hot corner code for dealing with dnd on X as a special case, but it doesn't seem to work for the hot edge the way it works for the hot corner, and I'm not sure what the difference is. I'll keep poking at it for a bit to see if I can figure out what's going on.

**Comment by seldon1000** [comment]
@jdoda I understand. I wish I could help, but I have no knowledge of js and GNOME shell. For now I’m keeping both hot edge and hot corner enabled so I can still drag items.

I’m updating the issue with my system’s info, I should’ve done so in the first place.

**Comment by jdoda** [comment]
I did some more investigation and couldn't find a way to fix this cleanly in X. Since it does work in Wayland, this will eventually no longer be an issue. Also see https://github.com/jdoda/hotedge/issues/9 for more discussion of drag behaviour.
