### ISSUE TITLE
Hot Edge broken by latest update

### ISSUE THREAD

**Issue by davidfox2116** [jdoda/hotedge#14]
The latest update broke things for me.  The extension won't load / stay on.  I've uninstalled/reinstalled.  I've built from downloaded source.  No dice.  If I create a new ID Hot Edge works, but I don't want to trash my current ID just to get this extension to work.

GNOME 40.4 (Wayland)
Fedora 34
Kernel 5.13.19-200

**Comment by jdoda** [comment]
Hey, thanks for opening an issue, and I'm sorry you're having problems. There were no real changes in the latest update (just adding Gnome 41 to the list of supported versions) so I'm not sure what could have happened. 

When you say "create a new ID" do you mean creating a new user, and installing the extension for that user?

**Comment by davidfox2116** [comment]
Yes, I had to create a new user and install the extension for the user for
it to work. I cannot get it to work again for the existing user. Is there
any persistent data I can remove to possibly get it to work?

**Comment by jdoda** [comment]
Can you run `journalctl -g hotedge -r` and paste the output? That may help us figure out what's going on.

Otherwise, if you blow away ~/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/ that should be all of the local state.

**Comment by davidfox2116** [comment]
Hi,

I have already blasted that directory a few times.  No luck.  I am getting
an error message on login about Gnome shell failing.  Could that be part of
the problem?


Here are the last few days of journal entries  - thanks

---

-- Journal begins at Sat 2020-11-14 06:49:29 PST, ends at Sun 2021-09-26
21:06:46 PDT. --
-- Boot 77bd29df9c964a01a7e4740c01aedc9c --
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:  extracting:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/metadata.json
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/extension.js
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/stylesheet.css
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/logger.js
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/gschemas.comp>
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/org.gnome.she>
Sep 26 10:18:03 delltop.localdomain gnome-shell[55970]:    creating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/
-- Boot 1815299b62da4de8884c6e5c8a398c09 --
-- Boot 77bd29df9c964a01a7e4740c01aedc9c --
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:  extracting:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/metadata.json
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/extension.js
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/stylesheet.css
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/logger.js
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/gschemas.compi>
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/org.gnome.shel>
Sep 25 10:11:38 delltop.localdomain gnome-shell[6756]:    creating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/
-- Boot 930378ff0f5141d3b2675842eb9c7f96 --
-- Boot 77bd29df9c964a01a7e4740c01aedc9c --
-- Boot 930378ff0f5141d3b2675842eb9c7f96 --
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:  extracting:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exte>
Sep 23 19:41:17 delltop.localdomain gnome-shell[16413]:    creating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:  extracting:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exte>
Sep 23 18:02:54 delltop.localdomain gnome-shell[11344]:    creating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/
Sep 23 17:59:14 delltop.localdomain gnome-shell[4755]: HotEdge | INFO |
Updating hot edges.
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:  extracting:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:   inflating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:   inflating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:   inflating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:   inflating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:   inflating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exte>
Sep 23 17:59:14 delltop.localdomain gnome-shell[6075]:    creating:
/home/bagwa/.local/share/gnome-shell/extensions/
***@***.***/schemas/
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:  extracting:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exten>
Sep 23 17:56:30 delltop.localdomain gnome-shell[3887]:    creating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/
-- Boot e9c6c50353f2487c890926fcc47636ea --
-- Boot 5ad9fe1ab09549f19fe7f302658e3515 --
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:  extracting:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exten>
Sep 23 13:06:15 delltop.localdomain gnome-shell[9158]:    creating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:  extracting:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/metadata.json
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/extension.js
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/stylesheet.css
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/logger.js
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/gschemas.compiled
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:   inflating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/org.gnome.shell.exten>
Sep 23 12:59:54 delltop.localdomain gnome-shell[8237]:    creating:
/home/dfox/.local/share/gnome-shell/extensions/
***@***.***/schemas/
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:  extracting:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/metadata.json
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/extension.js
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/stylesheet.css
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/logger.js
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/gschemas.compi>
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:   inflating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/org.gnome.shel>
Sep 23 12:57:25 delltop.localdomain gnome-shell[2868]:    creating:
/home/dfox/.local/share/gnome-shell/extension-updates/
***@***.***/schemas/
Sep 23 12:57:24 delltop.localdomain gnome-shell[2126]: HotEdge | INFO |
Updating hot edges.
-- Boot b141703b4a7b4c1c918d1c4403400e2d --
Sep 23 12:54:32 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 23 12:07:06 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 23 12:04:35 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 23 11:55:43 delltop.localdomain gnome-shell[2114]: Error while
downloading update for extension ***@***.***:
DownloadExtensionError (502)
Sep 23 11:09:59 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
-- Boot 930378ff0f5141d3b2675842eb9c7f96 --
-- Boot e9c6c50353f2487c890926fcc47636ea --
-- Boot b141703b4a7b4c1c918d1c4403400e2d --
Sep 23 10:47:16 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 23 10:11:50 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
-- Boot e9c6c50353f2487c890926fcc47636ea --
-- Boot 5ad9fe1ab09549f19fe7f302658e3515 --
-- Boot b141703b4a7b4c1c918d1c4403400e2d --
Sep 22 18:49:08 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 18:30:35 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges
Sep 22 17:49:35 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 16:20:47 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 16:05:40 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 15:20:17 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 14:44:26 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 14:30:24 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 14:09:53 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
Sep 22 11:55:41 delltop.localdomain gnome-shell[2114]: HotEdge | INFO |
Updating hot edges.
-- Boot f47a57adcf9245eda1dc2344dda0e1e9 --
Sep 22 11:52:34 delltop.localdomain gnome-shell[2210]: HotEdge | INFO |
Updating hot edges.
Sep 22 11:30:03 delltop.localdomain gnome-shell[2210]: HotEdge | INFO |
Updating hot edges.
Sep 22 09:30:34 delltop.localdomain gnome-shell[2210]: HotEdge | INFO |
Updating hot edges.
Sep 22 08:45:24 delltop.localdomain gnome-shell[2210]: HotEdge | INFO |
Updating hot edges.
Sep 22 08:15:41 delltop.localdomain gnome-shell[2210]: HotEdge | INFO |
Updating hot edges.
-- Boot 922564309b4c4b68ba1811756fc5f3df --
Sep 22 08:08:50 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
Sep 22 06:56:36 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
-- Boot b141703b4a7b4c1c918d1c4403400e2d --
-- Boot f47a57adcf9245eda1dc2344dda0e1e9 --
-- Boot 922564309b4c4b68ba1811756fc5f3df --
-- Boot f47a57adcf9245eda1dc2344dda0e1e9 --
-- Boot 922564309b4c4b68ba1811756fc5f3df --
Sep 21 19:52:24 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
Sep 21 19:10:58 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
Sep 21 14:02:49 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
Sep 21 12:58:21 delltop.localdomain gnome-shell[4378]: HotEdge | INFO |
Updating hot edges.
Sep 21 12:56:05 delltop.localdomain gnome-shell[2138]: HotEdge | INFO |
Updating hot edges.
-- Boot 788ff0a034f74d0287c555ccf02d7441 --
Sep 21 12:39:47 delltop.localdomain gnome-shell[2139]: HotEdge | INFO |
Updating hot edges.
-- Boot 7a8b111202784963a1ff0b0a96b13c55 --
.

**Comment by jdoda** [comment]
I'm sorry we weren't able to resolve this issue. Since it's been a long time now, I'm going to close this.
