### ISSUE TITLE
Add a setting to configure fallback-timeout and pressure-threshold in the extension settings (GUI)

### ISSUE THREAD

**Issue by sunsetpainting** [jdoda/hotedge#15]
It will be useful in order to overview don't get triggered by accident. Currently, it's not possible to configure this by a GUI.

**Comment by jdoda** [comment]
Thanks for the request. I'd been meaning to do this for a while, but had never got around to it. I've added GUI settings for this now (for the pressure case only, so it's not confusing). The update will be available on extensions.gnome.org soon.

**Comment by sunsetpainting** [comment]
Awesome, I already got the update. Thanks!
