### ISSUE TITLE
Add a gesture option to prevent accidental triggering

### ISSUE THREAD

**Issue by sunsetpainting** [jdoda/hotedge#16]
I think gestures might solve the problem of Hot Edge activating the Overview by accident. There could be gestures like:

- Move the cursor to the bottom of the screen, to the top and to the bottom;
- Place the cursor at the bottom of the screen and move it to the left and to the right and to the left (or the opposite).

**Comment by jdoda** [comment]
Hey sunsetpainting, thanks for the suggestion! I've given it some thought, and I'm not going to pursue this approach due to the  implementation complexity and the potential issues with discoverability and responsiveness.
