### ISSUE TITLE
Deprecate Bottom triggers Activities overview extension in favor of Hot edge?

### ISSUE THREAD

**Issue by papjul** [jdoda/hotedge#2]
Hi, I'm the creator of the extension Bottom triggers Activities overview:
https://extensions.gnome.org/extension/4120/bottom-triggers-activities-overview/
https://github.com/papjul/bottom-triggers-activities

Which, unless, I'm mistaken, is doing the same thing (+ yours supports multiple monitors).

As I don't plan on maintaining my extension anymore (I'm not really a Gnome extension developer, I was just annoyed by this UX issue), could I redirect users to your extension instead?

Feel free to pick up any relevant part of the code of my extension that you find useful to improve yours.

**Comment by jdoda** [comment]
Thanks for reaching out!

While the implementations are pretty different, I think you're right that from a user's point of view they are doing the same thing. I don't plan on adding new features to my extension, but I do plan to fix bugs and keep it working indefinitely, so if you want to deprecate your extension and redirect people to this one, I'm totally ok with that.

I think the fallback code I've got now for when pressure barriers aren't supported is pretty sketchy, so maybe I'll be able to use some of the code from your extension to fix that up.

**Comment by papjul** [comment]
Great that you plan to maintain it with future Gnome versions.
I've done the deprecation notice.

The only feature I can think of, that could be useful, is to be able to configure the toggle delay, otherwise keeping the extension simple is probably the best x)

Also, it seems that your extension disables the hot left corner, I don't think there is any particular reason to enforce that, there is already a control for that in Gnome Tweaks, you shouldn't override it ;)

**Comment by jdoda** [comment]
I do want to keep it simple, but also the tuning knobs for the pressure barriers are a bit weird, so I don't know if messing with them is actually useful. 

Good point about the setting in GNOME Tweaks, I'll fix that.
