### ISSUE TITLE
Desktop environment crash

### ISSUE THREAD

**Issue by arckster** [jdoda/hotedge#21]
I bought a TV and connected it to the laptop with an HDMI cable. Unfortunately, gnome crashes in multi-monitor mode. And it works incorrectly in mirroring mode. Does anyone else have this problem?
NVC3 / Intel® HD Graphics 3000 (SNB GT2)
Switching between x.org - Nvidia driver doesn't solve it either, and it's the same in wayland and x11 mode.
(translated from hungarian using google translate)

**Comment by jdoda** [comment]
This doesn't seem like it has anything to do with the Hot Edge extension. You might try filing this issue on the GNOME Shell issue tracker: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues .
