### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by plumlis** [jdoda/hotedge#26]
It seeems gnome 45 changed API
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by fthx** [comment]
I tried to fork but maybe changed too many things all at once.
Waiting for this I updated my extension that does roughly the same (but with no multi-monitor support):
https://extensions.gnome.org/extension/5099/hot-bottom/
You have to wait for the v4 (being reviewed).
I'll return back to Hot Edges once it will be upgraded, hoping it's just a new syntax issue.

**Comment by fthx** [comment]
Ok it works, thanks!
ATM it's being reviewed, you can DL the zip here:
https://extensions.gnome.org/review/44159

**Comment by fthx** [comment]
I finally made this, FYI.
https://extensions.gnome.org/extension/6230/bottom-overview/
I removed prefs and did add some ;
^^

**Comment by jdoda** [comment]
Thanks for the report. Hot Edge has now been updated to support GNOME Shell 45.

**Comment by plumlis** [comment]
hi, I tired the new version with gnome 45.
It can be enabled but doesn't work.

**Comment by jdoda** [comment]
@plumlis sorry it's not working for you. Can you let me know what version of what distro you're using, and provide the output of `journalctl -g hotedge /usr/bin/gnome-shell` . That will help me debug the issue. 

Thanks!

**Comment by plumlis** [comment]
hi, I installed from extensions.gnome.org, It's version 22

here are outputs.:



-- Boot eb9958281bd444bfba85c2dcbc07c409 --
Aug 30 08:55:09 plum-laptop gnome-shell[2280]: JS ERROR: TypeError: Layout.PressureBarrier is not a constructor
                                               _init@file:///home/plum/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/extension.js:130:33
                                               HotEdge@file:///home/plum/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/extension.js:113:1
                                               _updateHotEdges@file:///home/plum/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/extension.js:100:28
                                               _updateHotCorners@resource:///org/gnome/shell/ui/layout.js:486:14
                                               enable@file:///home/plum/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/extension.js:49:28
                                               _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:250:38
                                               async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:599:24
                                               _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:674:18
                                               createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
                                               enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:274:29
                                               _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:301:40
                                               async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:134:41
                                               @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by jdoda** [comment]
Ok, it's the same problem as in https://github.com/jdoda/hotedge/issues/27 . Unfortunately the problem (and the fix) is in GNOME Shell, and not the extension, so there's not much to be done about it for now. It'll be fixed whenever Fedora 39 pulls in a newer version of GNOME Shell.

**Comment by plumlis** [comment]
So this issue is Gnome-shell related and already fixed.
Extension will working in nexe gnome-shell version.
Right?

**Comment by jdoda** [comment]
Yes, that's correct.
