### ISSUE TITLE
Add GNOME 45 support

### ISSUE THREAD

**Issue by Kerrung** [jdoda/hotedge#28]
Please, add GNOME 45 support

**Comment by jdoda** [comment]
Hot Edge does support GNOME 45. If it's not working for you, please include what distro you're running and the output of running `journalctl -g hotedge /usr/bin/gnome-shell`.

**Comment by Flimm** [comment]
Is this the same extension? It seems to support GNOME 45.

https://extensions.gnome.org/extension/4222/hot-edge/

**Comment by jdoda** [comment]
Yes, that's the same extension. Hot Edge has full GNOME 45 support.
