### ISSUE TITLE
Feature Request: An "Only activate on Primary Monitor" Option

### ISSUE THREAD

**Issue by Malix-off** [jdoda/hotedge#33]
## Category

Feature Request

## Details

An "Only activate on Primary Monitor" Option

**Comment by jdoda** [comment]
Thanks for the request. It ought to be pretty straightforward, so I'll take a swing at it.

**Comment by jdoda** [comment]
I've pushed a new version to extensions.gnome.org that has this change.

**Comment by Malix-off** [comment]
Very nice to hear @jdoda ❤️

Is it pushed on GitHub yet ?

**Comment by Malix-off** [comment]
Thanks ❤️
