### ISSUE TITLE
Feature-Request: Disable top left hot corner

### ISSUE THREAD

**Issue by SpikePy** [jdoda/hotedge#4]
Could you implement the removal of the hot corner on the top left?
maybe by default or as a switch in the extension?

this would be awesome.

**Comment by jdoda** [comment]
Thanks for reaching out!

You can remove the hot corner by installing the GNOME Tweaks tool and using the "Top Bar" > "Activities Overview Hot Corner" option. Since the option already exists in the GNOME Tweaks tool, I don't want to duplicate the option in the extension as well. 

Hope that helps!
