### ISSUE TITLE
Add behavior of "auto-activities"

### ISSUE THREAD

**Issue by GaVenga** [jdoda/hotedge#5]
Life is easier if the bottom dash appears after the last app is closed.
acedron/auto-activities does that. 
.
? would you like to talk to each other - and create ONE app, together ?

**Comment by jdoda** [comment]
Thanks for the suggestion. That does seem like a cool feature, but I'm not looking to add any significant additional functionality to the extension. It does look like you should be able to use both extensions together, and in general I think small, focused extensions that can be safely combined is ideal.

**Comment by GaVenga** [comment]
the chance that several extensions interfere is proportional to their number.
