### ISSUE TITLE
Should only trigger on primary display

### ISSUE THREAD

**Issue by bulletmark** [jdoda/hotedge#8]
The opening paragraph of the README says the point of this extension is that it "minimizes the pointer travel required to access the dash when using the new GNOME Shell 40 overview layout". Given that, I think it makes more sense to only trigger on the bottom edge of the primary display when using a multi-display setup. It should not trigger on the other displays. This would help minimize accidental triggers.

**Comment by jdoda** [comment]
Hey, thanks for the suggestion. It's an interesting idea but after some thought I've decided not to implement it, for two reasons:

1. While minimizing pointer travel to the dash is the primary reason for the _location_ of the hot edge, accessing the dash isn't the only use for the hot edge. The way I (and others) use the extension is as the primary entry point to the activity overview, including when I want to switch windows. If the hot edge were removed from secondary displays then to switch windows I would need to mouse all the way over to the primary display to activate the hot edge, and then mouse all the way back to the original display to select the window.
2. With a feature like the hot edge where there is no visible UI on the screen to help guide users, it's very important that it behave in a consistent manner. If the user encounters a confusing behaviour, they don't have much information to use to figure out what's going on. Consider the case where a user installs Hot Edge on a laptop, uses it for a bit, and then connects the laptop to an external monitor. If the external monitor is set as the primary display, then suddenly the laptop display wouldn't have a hot edge, when previously it did. I'm not sure how a user would interpret what had happened in that situation, but a significant number would probably think the extension was broken.

These reasons don't preclude adding an option to disable the hot edge on secondary displays, but I'm not inclined to do that either. It would create a new branch in the code that I wouldn't use, and so wouldn't be tested on a regular basis. If it ever broke I would have no way to know unless someone opened an issue.

In any event, I appreciate that you have enough interest in the extension to open an issue, and I'm sorry I wasn't able to give a more positive response. Please continue to open issues in the future if you have other feature requests, and particularly if you encounter any bugs.
